name: Cypress Tests - In Class Project

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "**.json"
      - "**.yml"

jobs:
  in-class-project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Ensure Cypress binary is executable
        run: chmod +x ./node_modules/cypress/bin/cypress

      - name: Run Cypress tests
        run: npx cypress run --headless
