name: Cypress Tests - In Class Project

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "**.json"
      - "**.yml"

jobs:
  in-class-project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0

      - name: Cache gone
        run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:headless
